const BASE = process.env.NEXT_PUBLIC_BASE_PATH || '';

const AVATAR_MAP: Record<string, string> = {
  '甄嬛': '/avatars/zhenhuan.png',
  '林黛玉': '/avatars/lindaiyu.png',
  '乔布斯': '/avatars/jobs.png',
  '宫崎骏': '/avatars/miyazaki.png',
  '庄子': '/avatars/zhuangzi.png',
  '阿姆斯特朗': '/avatars/armstrong.png',
  '谷爱凌': '/avatars/guailing.png',
  '哈兰德': '/avatars/haaland.png',
  '居里夫人': '/avatars/curie.png',
  '郎平': '/avatars/langping.png',
  '马云': '/avatars/mayun.png',
  '马斯克': '/avatars/musk.png',
  '肖邦': '/avatars/chopin.png',
  '贝多芬': '/avatars/beethoven.png',
  '牛顿': '/avatars/newton.png',
  '泰勒斯威夫特': '/avatars/taylorswift.png',
  '达芬奇': '/avatars/davinci.png',
  '莫扎特': '/avatars/mozart.png',
  '张桂梅': '/avatars/zhangguimei.jpg',
  '安陵容': '/avatars/anlingrong.png',
  '苏轼': '/avatars/sushi.png',
  '苏东坡': '/avatars/sushi.png',
  '王阳明': '/avatars/wangyangming.png',
  '爱因斯坦': '/avatars/einstein.png',
  '孙悟空': '/avatars/sunwukong.png',
  '莎士比亚': '/avatars/shakespeare.png',
  '李白': '/avatars/libai.png',
  '武则天': '/avatars/wuzetian.png',
  '诸葛亮': '/avatars/zhugeliang.png',
  '梵高': '/avatars/vangogh.png',
  '王菲': '/avatars/wangfei.png',
};

export function getAvatar(name: string): string {
  const path = AVATAR_MAP[name];
  return path ? `${BASE}${path}` : '🫧';
}

export function isImageAvatar(avatar: string): boolean {
  return avatar.includes('/avatars/');
}

// ===== 新角色池头像映射（独立于旧池） =====
const NEW_AVATAR_MAP: Record<string, string> = {
  '刘慈欣': '/avatars/刘慈欣.png',
  '村上春树': '/avatars/村上春树.png',
  '手冢治虫': '/avatars/手冢治虫.png',
  '安藤忠雄': '/avatars/安藤忠雄.png',
  '冯骥': '/avatars/冯骥.png',
  '郭帆': '/avatars/郭帆.png',
  '施瓦辛格': '/avatars/施瓦辛格.png',
  '王小波': '/avatars/王小波.png',
  '北野武': '/avatars/北野武.png',
  '弗里达·卡罗': '/avatars/弗里达·卡罗.png',
  '鲍勃·迪伦': '/avatars/鲍勃·迪伦.png',
  '费曼': '/avatars/费曼.png',
  '特斯拉': '/avatars/特斯拉.png',
  '张伟丽': '/avatars/张伟丽.png',
  '马拉拉': '/avatars/马拉拉.png',
  '王小云': '/avatars/王小云.png',
  '韦慧晓': '/avatars/韦慧晓.png',
  '邓亚萍': '/avatars/邓亚萍.png',
  '王计兵': '/avatars/王计兵.png',
  '毛相林': '/avatars/毛相林.png',
  '黄大发': '/avatars/黄大发.png',
  '张顺东、李国秀夫妇': '/avatars/张顺东、李国秀夫妇.png',
  '刘秀祥': '/avatars/刘秀祥.png',
  '王顺友': '/avatars/王顺友.png',
  '褚时健': '/avatars/褚时健.png',
  '任正非': '/avatars/任正非.png',
  '摩西奶奶': '/avatars/摩西奶奶.png',
  '桑德斯上校': '/avatars/桑德斯上校.png',
  '王德顺': '/avatars/王德顺.png',
  '曼德拉': '/avatars/曼德拉.png',
  '林肯': '/avatars/林肯.png',
  '俞敏洪': '/avatars/俞敏洪.png',
  '李安': '/avatars/李安.png',
  '司马迁': '/avatars/司马迁.png',
  '曾国藩': '/avatars/曾国藩.png',
  '廖智': '/avatars/廖智.png',
  '南仁东': '/avatars/南仁东.png',
  '樊锦诗': '/avatars/樊锦诗.png',
  '小野二郎': '/avatars/小野二郎.png',
  '王津': '/avatars/王津.png',
  '苏翊鸣': '/avatars/苏翊鸣.png',
  '王兴兴': '/avatars/王兴兴.png',
  '史铁生': '/avatars/史铁生.png',
  '张海迪': '/avatars/张海迪.png',
  '夏伯渝': '/avatars/夏伯渝.png',
  '邰丽华': '/avatars/邰丽华.png',
  '南丁格尔': '/avatars/南丁格尔.png',
  '林徽因': '/avatars/林徽因.png',
  '杨绛': '/avatars/杨绛.png',
  '张爱玲': '/avatars/张爱玲.png',
  '汪曾祺': '/avatars/汪曾祺.png',
  '辜鸿铭': '/avatars/辜鸿铭.png',
  '童恩正': '/avatars/童恩正.png',
  '史怀哲': '/avatars/史怀哲.png',
  '薇薇安·迈尔': '/avatars/薇薇安·迈尔.png',
  '金庸': '/avatars/金庸.png',
  '阿加莎': '/avatars/阿加莎.png',
  '简·奥斯汀': '/avatars/简·奥斯汀.png',
  '马尔克斯': '/avatars/马尔克斯.png',
  '三毛': '/avatars/三毛.png',
  '陶华碧': '/avatars/陶华碧.png',
  '李子柒': '/avatars/李子柒.png',
  '华罗庚': '/avatars/华罗庚.png',
  '阿甘': '/avatars/阿甘.png',
  '安迪': '/avatars/安迪.png',
  '路飞': '/avatars/路飞.png',
  '图灵': '/avatars/图灵.png',
  '孔子': '/avatars/孔子.png',
  '曹操': '/avatars/曹操.png',
  '司马懿': '/avatars/司马懿.png',
  '王尔德': '/avatars/王尔德.png',
  '笛卡尔': '/avatars/笛卡尔.png',
  '刘姥姥': '/avatars/刘姥姥.png',
  '楚门': '/avatars/楚门.png',
  '里昂': '/avatars/里昂.png',
  '玛蒂尔达': '/avatars/玛蒂尔达.png',
  '伍尔夫': '/avatars/伍尔夫.png',
  '邓布利多': '/avatars/邓布利多.png',
  '王熙凤': '/avatars/王熙凤.png',
  '乔治·奥威尔': '/avatars/乔治·奥威尔.png',
  '周星驰': '/avatars/周星驰.png',
};

export function getNewAvatar(name: string): string {
  const path = NEW_AVATAR_MAP[name];
  return path ? `${BASE}${path}` : '🫧';
}
